### ISSUE TITLE
getaddress, command not found

### ISSUE THREAD

**Issue by karalabe** [DigixGlobal/digixbot-contracts#1]
Tried to set an address and then retrieve it, however hot the following reply:

```
I was not able to complete your last request due to the following errors:
Unknown command 'getaddress'
```

Edit: This command was suggested in the registration message.

**Comment by kcchng** [comment]
Hello! Thanks for trying it out. The command to retrieve the address would be 'accountinfo' , only commands in the help file will work.

**Comment by tymat** [comment]
We'll fix up the registration message.  Might still be using the old help file.

**Comment by karalabe** [comment]
Another issue. I've tried the `setaddress <addr>`, but no reply comes, and afterwards `accountinfo` returns `External Account   0x0000000000000000000000000000000000000000`.

**Comment by karalabe** [comment]
Also tried `depositinfo`, but no reply came to that either.

**Comment by czepluch** [comment]
Confirming that this is a problem. I've been getting no response on any commands for the last hour.

**Comment by tymat** [comment]
There were issues with the oracle's connectivity to Reddit so it was unable to fetch the messages.  It should work now and previous commands should have been processed and notifications sent.

**Comment by karalabe** [comment]
@tymat setaddress and depositinfo still don't do anything though.

**Comment by tymat** [comment]
I sent you the setaddress command and you should have received a notice about it.  Can you try sending a setaddress again?

**Comment by karalabe** [comment]
Tried it again now, can confirm that `setaddress` works.

**Comment by karalabe** [comment]
And can also confirm that now `depositinfo` also seems to work.

**Comment by tymat** [comment]
Also there was a mistake in the registration message.  The getaddress command is replaced with accountinfo which should give you the account balance and your current settings.

**Comment by karalabe** [comment]
Btw, just a small thing that might make user experience a bit better. In the deposit info message, where you detail how you can send a transaction to the wallet account, you specify the amount in wei. It might be a bit friendlier to use ether as the denomination:

```
web3.eth.sendTransaction({from: "0x...", to: "0x...", value: web3.toWei(2, "ether")});
```

**Comment by tymat** [comment]
Updated the message with a few examples.  Our plan is to add a list of links to some good downloadable/online wallets once they are ready for public use.
